services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../public/:/srv
      - caddy_data:/data
      - caddy_config:/config
    network_mode: host
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
